### PR TITLE
Moving gatsby-ssr and adding injectHTML check.

### PR DESCRIPTION
**Pull request by maddijoyce**

### CODE REVIEW

**Comment by maddijoyce** [comment]
This code works for me now.
- Move it out of the src/ folder and replaced import with require.
- Added react as a dependency in NPM.
- Added the check for injectHTML in gatsby-ssr.

**Comment by mperkh** [comment]
This makes no sense at all. Please have a look at how other gatsbyJS plugins are written, eg. https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-manifest

- Babel compiled js files should not be committed to the repo, there is a `.gitignore` for that reason https://github.com/Creatiwity/gatsby-plugin-favicon/pull/6/files#diff-a084b794bc0759e7a6b77810e01874f2
- ~~Adding the config change to the Readme does not make much sense, without the corresponding implementation of that functionality also in `gatsby-node.js`~~
- React is not necessary as a dependency, since its handled by bableJS

Please can you describe, what is '_not working for you_'?

**Comment by mperkh** [comment]
Added `injectHTML` config param to es6 version of `gatsby-ssr.js`, https://github.com/Creatiwity/gatsby-plugin-favicon/pull/6/commits/da8849b8d8c76993d1c81c661c17786e31c88964, which makes this pullreq. obsolete.
@julien1619 Is there a chance to release version 2.1.0 of this plugin to NPM?

**Comment by maddijoyce** [comment]
Hi Michael,
With the gatsby-ssr file in the src folder, the code wasn’t being accessed at all. Maybe it’s because of the pieces missing that you added in your commit.
I guess I figured I’d just follow what was happening in this repo, because the Gatsby-node file was in the base directory, there was no need for Babel in either case. However without react as a dependency, I was getting validation errors from ‘setHeadComponents’.
I added the config to the readme because I’d added the functionality to Gatsby-ssr. I dont think Gatsby-node needs to be impacted by injecthtml at all.
No problems at all going with your code if it works though.
Cheers.

**Comment by mperkh** [comment]
> I added the config to the readme because I’d added the functionality to Gatsby-ssr. I dont think Gatsby-node needs to be impacted by injecthtml at all.

true. Just saw, the config param is already addresses in `gatsby-node`. https://github.com/Creatiwity/gatsby-plugin-favicon/blame/master/gatsby-node.js#L22

Am also not sure, if committing `package-lock.json` files is a good idea.

**Comment by maddijoyce** [comment]
#6 Fixes this issue.

**Pull request closed without merging**
