### PR TITLE
Upgrade for Gatsby v2 (onCreateWebpackConfig/setWebpackConfig)

### PR DESCRIPTION
**Pull request by TuckerWhitehouse**
As part of the Gatsby v2 upgrade, modifying the webpack config has received a new redux based api: https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/#change-modifywebpackconfig-to-oncreatewebpackconfig

### CODE REVIEW

**Comment by chasemccoy** [comment]
@Creatiwity can you merge and publish this? I am using Gatsby 2 now and this plugin is broken. This would be a great fix!

**Comment by janosh** [comment]
Any reason why this PR is not being accepted? Would be great to have v2 compatibility.

**Comment by julien1619** [comment]
Thank you for this PR. In fact I was busy and working on a last (big) update for Gatsby v1 but I didn't see that it was already in beta.

I will merge it in a feature branch tomorrow, release a last version on v1 without my current changes to speed everything up and publish this v2-based version shortly after.

**Comment by janosh** [comment]
@julien1619 Nice! Looking forward to it.

**Comment by julien1619** [comment]
So I've merged it after fixing some conflicts, but I can't make it work with Gatsby v2. I can't say the exact error cause. Can you test it @JanoshRiebesell using the branch gatsby-v2 from this repository to see if you reproduce it? Thank you very much!

The error comes from favicons-webpack-plugin not finding `webpack/lib/SingleEntryPlugin` when building the site with Gatsby. It's the first I'm using Gatsby v2 so I don't know if it's Gatsby not exposing some dependency stuff, or favicons-webpack-plugin using webpack the wrong way, or simply my setup.

To test it you would need to pull this branch locally, and reimport favicons-webpack-plugin in it using the direct git link (a fix is available but not published yet). Thanks again!

**Comment by julien1619** [comment]
Ok, so I've found it! Will be releasing this new version very soon with a lot of changes.

**Comment by janosh** [comment]
@julien1619 That's great! Let me know if I can help write docs for those changes if applicable.

**Comment by julien1619** [comment]
Thanks @JanoshRiebesell, the big update is available ;)

**Pull request merged**
