### PR TITLE
Fix NPM build and publish process, add support for `injectHTML` config parameter

### PR DESCRIPTION
**Pull request by mperkh**
@maddijoyce Maybe this also addresses https://github.com/Creatiwity/gatsby-plugin-favicon/pull/5#issuecomment-342019625

### CODE REVIEW

**Comment by gregorskii** [comment]
Is this going to be merged in? Just ran into this same issue.

Thanks

**Comment by mperkh** [comment]
@gregorskii Hope so. In the meantime, please use and test a temporary version of the plugin, which covers the mentioned fixes.

`npm remove gatsby-plugin-favicon`
`npm install gatsby-plugin-favicon-mperkh`

also use the corresponding plugin name in `gatsby-config.js`:

```resolve: `gatsby-plugin-favicon-mperkh`,```

**Comment by gregorskii** [comment]
Will is in the am. Thank you!

**Comment by gregorskii** [comment]
Yep, this works! Excellent, appreciate you publishing an alt version.

@Creatiwity LGTM! :)

**Comment by julien1619** [comment]
Thank you all! I was a little bit busy on some other things, but here I am :)

**Comment by gregorskii** [comment]
As well all are... haha, if only it was OSS all day. Thank you 🙏

**Comment by mperkh** [comment]
@julien1619 Mercie beaucoup! Will unpublish the forked version from npmjs next week, ok?

**Pull request merged**
