### PR TITLE
Add logo to options to allow customised favicon path.

### PR DESCRIPTION
**Pull request by maddijoyce**
Hey,

I was using your plugin and wanted to customise the logo path. Thought I'd create the pull request to see if you're interested?

Cheers,
Maddi

### CODE REVIEW

**Comment by julien1619** [comment]
I think it's a good idea! However I would introduce it a bit differently and the configuration file would look like that:
```json
{
  "logo": "./src/favicon.png",
  "icons": {
    "android": true,
    "appleIcon": true,
    "appleStartup": true,
    "coast": false,
    "favicons": true,
    "firefox": true,
    "twitter": false,
    "yandex": false,
    "windows": false
  }
}
```
This way, the configuration layout would stick to the one used by the `FaviconsWebpackPlugin`. I'm aware that it's a breaking change but I'm Ok with that :)

Can you do the changes and I'll merge it and publish a new release? Thank you!

**Comment by maddijoyce** [comment]
That config makes a whole lot more sense. I've updated it now.

Also wanted to let you know the SSR stuff isn't working for me, so I'm going to have a look at it. I'll do that in another pull request though.

**Comment by julien1619** [comment]
Thank you! I'll look at it quickly as soon as you post it.

**Comment by mperkh** [comment]
> Also wanted to let you know the SSR stuff isn't working for me, so I'm going to have a look at it. I'll do that in another pull request though.

Check out https://github.com/Creatiwity/gatsby-plugin-favicon/pull/6. Just reworked the whole npm build and publish logic, maybe that fixes the problem. If you use this plugin as a local plugin for development, you need to issue `npm i` in the plugin folder to let it compile the `gatsby-ssr.js` file by hand.

**Comment by mperkh** [comment]
Also I would propose for a config like

```js
{
  "logo": "./src/favicon.png",
  "injectHTML": true, // default: true
  "icons": {
    "android": true,
    "appleIcon": true,
    "appleStartup": true,
    "coast": false,
    "favicons": true,
    "firefox": true,
    "twitter": false,
    "yandex": false,
    "windows": false
  }
}
```
Therefore HTML injection can be turned on/off globally and icon generation can be turned on/off (and as a consequence the icons's HTML injection) in a granular manner.

**Comment by maddijoyce** [comment]
Yeah, I think the injectHTML config makes a lot of sense.

I went the other way on my end and removed the babel stuff from the file. I also needed to add React as a dependency.

**Pull request merged**
